### ISSUE TITLE
"Could not find a package configuration file provided by "pedsim_msgs" " occurs when I try to catkin_make the package in a ROS workspace

### ISSUE THREAD

**Issue by ModernGangster** [eliasgoldsztejn95/PTDRL#7]
CMake Error at /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "pedsim_msgs" with
  any of the following names:

    pedsim_msgsConfig.cmake
    pedsim_msgs-config.cmake

  Add the installation prefix of "pedsim_msgs" to CMAKE_PREFIX_PATH or set
  "pedsim_msgs_DIR" to a directory containing one of the above files.  If
  "pedsim_msgs" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  PTDRL-main/simulation/pedsim_ros/pedsim_gazebo_plugin/CMakeLists.txt:10 (find_package)
________________________________________________________________________________________
Is there any 3rd party package should be downloaded? The Readme is somehow not well explained for newcomer on ROS...
Thanks for your attention.

**Comment by eliasgoldsztejn95** [comment]
Let me know if you need any help.
I still need to erase some functions that are not used in the code, and document it a bit more.
